export const PLAYER_DAMAGE_KNOCKBACK_DISTANCE = 160;
export const PLAYER_DAMAGE_FLASH_COLOR = 0xffffff;
export const PLAYER_DAMAGE_FLASH_ALPHA = 0.55;
export const PLAYER_DAMAGE_FLASH_MS = 70;
export const PLAYER_INVULNERABILITY_MS = 1000;
export const PLAYER_INVULNERABILITY_BLINK_MS = 110;
